### ISSUE TITLE
Doesn't appear compatible with rgthree ksamplerconfig

### ISSUE THREAD

**Issue by careo** [audioscavenger/save-image-extended-comfyui#1]
It doesn't seem able to read values that were passed from rgthree KSamplerConfig, through rgthree context node, and finally on to an Inspire KSamplerAdvanced.

For example, given the default filename keys of `sampler_name, scheduler, cfg, steps`, I'm getting a filename of `sampler_name, scheduler, cfg, steps`. Where `966` is the node id of the context node, and the integer looks like the index in the output of the context.

I'll try and cook up a simple workflow example that reproduces this.

**Comment by careo** [comment]
I've reproduced it with just a few tweaks to the default workflow and it seems to be an issue more with rgthree's ksampleroconfig. 

![ComfyUI_euler_normal_8 0_ '10', 0 _0001](https://github.com/audioscavenger/save-image-extended-comfyui/assets/1156/e2dd95ca-9f08-463a-8aaf-8ec2f09fb838)

**Comment by audioscavenger** [comment]
I appreciate your willingness to provide me with a sample that I can work on, thank you very much. Will look at it in a few.
A week later... just realized I was not recieving notifications for my own project, bummer.

**Comment by audioscavenger** [comment]
okay i can reproduce. 
- primitive int -> steps ksampler: no bug
- rgthree STEPS/REFINER_STEPS -> steps ksampler: bug
- rgthree STEPS -> CR int to str -> String to Integer -> steps ksampler: bug too

clearly smth with rgthree's Ksampler config, which I have never tried. So you plug in steps, and somehow, you also override cfg/sampler/scheduler ? that's dark magic.
I opened ksampler_config.py, and it actually does nothing but output RETURN_NAMES with corresponding RETURN_TYPES.

No clue how that even works, or how it's even possible that we link only steps, and somehow we also alter  "CFG", "SAMPLER", and "SCHEDULER"
sorry, you will have to ask him. He works at Google and not sure he will have time for that

**Comment by audioscavenger** [comment]
here is the fix: use "**steps_total**" instead of steps, and you get the steps value you want.

**Comment by audioscavenger** [comment]
here is the fix: use "**steps_total**" (or 10.steps_total if you have multiple ksampler config) instead of steps, and you get the steps value you want.
