### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by nasoooor29** [audioscavenger/save-image-extended-comfyui#11]
**Problem:**
i had this error when running the extention for the first time on [18bc842](https://github.com/audioscavenger/save-image-extended-comfyui/commit/18bc84204e610708c013b95b3966458bf03cf102) commit

**Example:**
![WindowsTerminal_2g9GhJ1WRS](https://github.com/audioscavenger/save-image-extended-comfyui/assets/62251201/f253e3ba-d4e4-4fc9-a9f8-23e6d58717bc)

![Code_Qp5Z0qpJOL](https://github.com/audioscavenger/save-image-extended-comfyui/assets/62251201/093dc2b0-c058-43c8-aabd-6069002ca7c4)

**solution:**
it's just a simple syntax error you can just convert it into a string or something or remove the last "."
version = 2.6.5 -> version = 2.6

**Comment by audioscavenger** [comment]
i am surprised at how many ppl got this error that i pushed for like 10mn only... but glad you found out it was solved right away lol
