### ISSUE TITLE
the key "resolution" doesn't work when generate custom name for filename

### ISSUE THREAD

**Issue by ybybzj** [audioscavenger/save-image-extended-comfyui#13]
when put "resolution" in filename_keys input, the result filename for save is like "xxx-resolution-...", resolution is not replaced by actual "{width}x{height}" format resolution string.
<img width="1261" alt="image" src="https://github.com/audioscavenger/save-image-extended-comfyui/assets/163048/07541ea5-c7f6-497d-a2d1-60cd7218df9b">
<img width="271" alt="image" src="https://github.com/audioscavenger/save-image-extended-comfyui/assets/163048/49f4e200-82cb-4dee-a390-eec09103ac4d">

**Comment by audioscavenger** [comment]
as stated in the documentation, when the keyword is not found in the prompt, it is used as is. resolution is not what the Load Image node outputs, sorry

**Comment by audioscavenger** [comment]
there is certainly a node from WAS or pygossss similar, that will take an image and spits out a resolution, that you can then use in your image name! ask in matrix, and good luck !

**Comment by ybybzj** [comment]
I already tried that, do not work. So I made my fork, and it works for me.
But still, thanks for the reply!
By the way, there is a place in the doc to say "resolution" should work .
<img width="1040" alt="image" src="https://github.com/audioscavenger/save-image-extended-comfyui/assets/163048/0034e1b5-e9ae-4e04-b327-f91912ddb568">
maybe it's my misunderstanding.

**Comment by audioscavenger** [comment]
hi, you are not mistaken since you it is in the doc. However, it was lost when I rewrote the recursive function entirely.
So i found out where it was and how to bring it back it, hare is v2.76 just for you
thanks
