### ISSUE TITLE
When using a specific Checkpoint Loader It is not saved under the Checkpoint name.

### ISSUE THREAD

**Issue by Neytiri7** [audioscavenger/save-image-extended-comfyui#15]
I'm using a node by creating a folder with a checkpoint name and saving it...
When using a specific Checkpoint Loader, `{'content':` As this item enters, it fails, and the folder is not saved.

The Checkpoint Loader is a node in pysssss.
https://github.com/pythongosssss/ComfyUI-Custom-Scripts

Is it something that can't be solved?

![image](https://github.com/audioscavenger/save-image-extended-comfyui/assets/139053327/0814f4d1-9048-413a-b0bc-2bbc76659c6b)

`SaveImageExtended 2.76 error: An error occurred while creating the subfolder or saving the image: [WinError 267] 디렉터 리 이름이 올바르지 않습니다: "O:\\OneDrive\\AI\\Areum\\{'content': '1.Pureum"
!!! Exception during processing!!! object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 95, in get_output_data
    output_is_list = [False] * len(results[0])
                               ^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()`

**Comment by Neytiri7** [comment]
`{'content': ` I hope it's only detected after the item...

**Comment by audioscavenger** [comment]
is "1.Pureum" the name of your ckpt?
I have seen another node from icantremember, that has similar issue. It used dynamic hacks that bypass the prompt entirely, leading to absence of data, or as you can see, a json of some sort. Easy enough to detect and parse when it happens. I think I can fix that.

will have a look in a few days, thanks

**Comment by Neytiri7** [comment]
Thank you, and I'll be waiting for you.

**Comment by audioscavenger** [comment]
fixed in v2.81
