### ISSUE TITLE
denoise parameter formated with only 1 decimal place

### ISSUE THREAD

**Issue by fgmanfredini** [audioscavenger/save-image-extended-comfyui#22]
i am  using the following save format:  "sampler_name, steps, scheduler, guidance, denoise, %F" but the denoise is formated as '0.9' instead of 0.9X....  so, for example i have a bunch of files named wth "xxx0.9" and i do not know if i used 0.90, 0.95 or 0.99 in the denoise...   it woulb be nice if float values were formated using 2 decimal places of if there was an option fo specify the number of decimal places to use.

**Comment by alex-mitov** [comment]
Same problem here. :( I would love to use this node, and this is a problem for me too.

**Comment by audioscavenger** [comment]
fixed, thanks for your patience. please upgrade
