### ISSUE TITLE
request: decimal accuracy

### ISSUE THREAD

**Issue by dryodryo** [audioscavenger/save-image-extended-comfyui#33]
Hello,

Thank you again for making this fantastic node!

Unfortunately, I am seeing parameter values being rounded to only one decimal place.

For example, I have an actual Strength value of 0.65, but the node is rounding this up to 0.7. There's a huge difference between those two values in terms of the results they give.

If the stored value is not accurate, it defeats the purpose entirely.

Please store the actual values as displayed in the node parameters, and do not round or truncate.

Thanks again

**Comment by abline11** [comment]
I'm having the opposite problem.  My 2.9 for Guidance is coming back as 2.9000000000000004.

**Comment by dryodryo** [comment]
Weirdness

**Comment by audioscavenger** [comment]
it's called python weirdness with floats. Try something simple as 0.14*100 and see the result for yourself.
But I agree rounding is so bad it's actually a bug.
okay I fixed it to the last significant digit, up to 10 max. 
Keep in mind this did not affect actual value in prompt saved inside the image. just the filename.

**Comment by dryodryo** [comment]
Fantastic, thank you!
