### ISSUE TITLE
ckpt_name includes subfolder path

### ISSUE THREAD

**Issue by MantisCore** [audioscavenger/save-image-extended-comfyui#36]
I use several levels of subfolders to organize my checkpoints. From the description I surmised that ckpt_name would contain only the checkpoint name and discard the rest of the path but I find that when using ckpt_name as part of the filename it creates subfolders in my output folder. Is this working as intended?

**Comment by Targren** [comment]
Having the same issue, and this node seems to be the only option out there that offers the option of the saving with the name sans the whole path

**Comment by rea-ducks** [comment]
I also have that problem.
I don't know what was really indended, but I've adjusted it according to my expectation. Just created pull request #38.

**Comment by Targren** [comment]
> I also have that problem. I don't know what was really indended, but I've adjusted it according to my expectation. Just created pull request #38.

This is great, thank you!  I've pulled yours down and tested it out, and it works a treat. Way better than my workaround of using Comfyroll "Split Strings" by '/' and having to move any checkpoints to make sure they're at the right depth.

**Comment by audioscavenger** [comment]
merged, although not tested extensively. It seems to do what you want, and I agree it should have been split the way you did. thank you.
A downside is that the *_path variable will never be used unless you also add the *_name.
