### ISSUE TITLE
Node doesnt save an image.

### ISSUE THREAD

**Issue by yovsac** [audioscavenger/save-image-extended-comfyui#37]
Hi,

the node has a red outline and wont save the image. 
![Uploading Screenshot 2024-10-28 153700.jpg…]()

**Comment by audioscavenger** [comment]
can you reupload the picture, please?
also Comfy was updated since June, did you also upgrade along all your custom nodes? 
This plugin was tested and developed with Python 3.10, and still is. 
Is your issue still up?

**Comment by audioscavenger** [comment]
uninstall and reinstall, maybe you're on the legacy version
