### ISSUE TITLE
Automatic date/time conversion in file/folder names doesn't work

### ISSUE THREAD

**Issue by paleocomburo** [audioscavenger/save-image-extended-comfyui#39]
I've been trying multiple variations, but even if I use the exact same values as present in the screenshot where it is explained, it doesn't work.

![image](https://github.com/user-attachments/assets/ad0c2f4b-3034-4c18-91fc-09d6c44e1475)

Leads to:

![image](https://github.com/user-attachments/assets/ed8dccc3-28e8-4055-9852-c1cde8834bcf)

**Comment by paleocomburo** [comment]
Never mind. Obviously as soon as I reported this I figured it out.
I was still running an old version (pre-fork). I had noticed the Custom Module Manager mentioned this, so I had uninstalled and reinstalled (I'm 100% sure of it), but it seems like it kept the wrong version.
Uninstalling again, and verifying the custom node was indeed gone from my filesystem. then reinstalling it fixed it.

**Comment by audioscavenger** [comment]
i should have created a new project name I must confess that I thought it would be easier for you guys to upgrade. but it's not. sorry.
