### ISSUE TITLE
subdirectory creation

### ISSUE THREAD

**Issue by khellendros74** [audioscavenger/save-image-extended-comfyui#40]
as from your example, for subdirectory creation
![image](https://github.com/user-attachments/assets/bab4f892-5728-4a29-aa66-544825993d98)
![image](https://github.com/user-attachments/assets/8e44207c-52c6-4fd9-a78f-f8b63855aae4)

it translate coma as your defined separator
resulting having the separator in the directory name prefixed with separator
i try without positif result:
ckpt_path,./ckpt_name
ckpt_path./ckpt_name
ckpt_path,/,ckpt_name
ckpt_path/ckpt_name

![image](https://github.com/user-attachments/assets/192649f0-5d84-48ae-805b-0e104af8fb61)

**Comment by audioscavenger** [comment]
oh wow, it used to work, and after i fixed lots of stuff now it does not... well well well thank you for giving me more work lol

Valid issue, working on it

**Comment by khellendros74** [comment]
thanks ;)
