### ISSUE TITLE
small bug that you save negative_text into prompt_keys_to_save['positive_prompt'], so that json file can not save positive prompt correctly

### ISSUE THREAD

**Issue by lemonhall** [audioscavenger/save-image-extended-comfyui#8]
https://github.com/audioscavenger/save-image-extended-comfyui/blob/2a2e38397a9d87701f4c8d6caa2cc6a8a4f357ca/save_image_extended.py#L424

                print("执行将positive_text存入prompt_keys_to_save['positive_prompt']")
                prompt_keys_to_save['positive_prompt'] = positive_text
                print("查看一下存入的目标变量是否正确：prompt_keys_to_save['positive_prompt'] ")
                print(prompt_keys_to_save['positive_prompt'])
              
              if negative_text is not None:
                print("进入了：if negative_text is not None:")
                if isinstance(negative_text, list):
                  print("进入了：if isinstance(negative_text, list):")
                  if len(negative_text) == 2:
                    if isinstance(negative_text[0], str) and len(negative_text[0]) < 6:
                      if isinstance(negative_text[1], (int, float)):
                        continue
                print("执行将negative_text存入prompt_keys_to_save['positive_prompt']")
                **prompt_keys_to_save['negative_text'] = negative_text**

**Comment by audioscavenger** [comment]
[fixed](https://github.com/audioscavenger/save-image-extended-comfyui/commit/a9504f9e6330b4a34f9cb773db31c2f91ef40a60)
